name: "App"

on:
  push:
    paths:
      - 'app/**'
jobs:
  deploy:
    runs-on: [ubuntu-latest]  
    steps:
      - name: Bump version
        uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
